# Generated by Django 4.1.4 on 2023-01-16 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0005_post_date_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 16, 39, 16, 35642)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 16, 39, 16, 34135)),
        ),
    ]
