# Generated by Django 4.1.4 on 2023-01-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0008_alter_comments_author_alter_comments_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='post',
        ),
    ]
